### ISSUE TITLE
Left click the app doesn't make the window open

### ISSUE THREAD

**Issue by eduardoxfurtado** [emoacht/Monitorian#118] opened 2021-01-13 21:52 UTC
Version 2.9.0.0
No response when I click the app.
Can't understand how to reproduce, but it happens when the app is installed through windows store or from the source.
Launching the app as administrator doesn't change anything.
Sometimes it start working after restarting the app, but only sometimes.
Right click still works fine.

Edition	Windows 10 Pro
Version	20H2
Installed on	‎2020-‎12-‎24
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by eduardoxfurtado** [comment] 2021-01-13 21:59
I managed to reproduce:
I use the windows taskbar on the left side of my screen.
The app works fine when the taskbar has two icons wide in the notification area, but when I make it 3 icons wide, the rendering gets confused and probably is rendering Monitorian in an out-of-bounds position of the screen.
Increasing the width for a little bit more than 3 icons (3 and a half, for example) fixes it.
So, it's a strong indication that there is a bug with how it calculates where the window is supposed to be rendered.

Moving the main taskbar for a secondary screen that is in portrait mode, and reproducing by making the windows taskbar 3 icons wide, the Monitorian windows is drawn in the middle of the screen next to the taskbar, instead of in the bottom of the screen next to the clock and the taskbar, A.K.A. the notification area.

**Comment by emoacht** [comment] 2021-01-14 00:37
Thank you for the report.
I could not reproduce it but probably something wrong happens to geometry data obtained by Win32 API in 
StickWindowMover.TryGetAdjacentLocationToTaskbar method. https://github.com/emoacht/Monitorian/blob/master/Source/ScreenFrame/Movers/StickWindowMover.cs#L68

To fix it, it is necessary to check geometry data step by step when it happens. BTW, what is DPI of your monitors?

**Comment by eduardoxfurtado** [comment] 2021-01-14 00:57
Main one is 1920x1080. Second one is 1440x2560.

**Comment by emoacht** [comment] 2021-01-14 01:04
They are not DPI. DPI is usually represented by percentage such as 100% or 125%.

**Comment by eduardoxfurtado** [comment] 2021-01-14 01:12
I thought it was weird when you asked for DPI and I assumed it was the resolution.
Actually the DPI refers to the density, so it's calculated based on the resolution and the size of the panel.
What you are asking is the DPI scaling! Which is 100% on both cases. It's a nice guess that you had, by the way, which could very well be the root of the problem.

I recorded a short video to show you the behavior in action: https://youtu.be/e9yh8kxdd8E

**Comment by emoacht** [comment] 2021-01-14 01:28
Yes I mean DPI scaling. It can be a source of wrong geometry data but if they are 100%, it is not the case.
The video does not help much.
It is possible to check NotifyIconContainer.MouseLeftButtonClick event when you click the icon.
https://github.com/emoacht/Monitorian/blob/master/Source/ScreenFrame/NotifyIconContainer.cs#L214

**Comment by emoacht** [comment] 2021-01-27 02:53
I have never had similar issue so far and have no idea on what internally happens on your system.
I close this issue but when you get new information, feel free to post it here.

**Closed by emoacht** 2021-01-27 02:53 UTC
