### ISSUE TITLE
Monitorian doesn't disappear after losing focus

### ISSUE THREAD

**Issue by realoctavian** [emoacht/Monitorian#482] opened 2023-07-10 15:50 UTC
Hi, while using this app I'm regularly encountering an issue where after adjusting the screen brightness and going back to the application I was previously using, the Monitorian app does not dissapear.

Steps to reproduce:
1. Launch a fullscreen application (usually I just play games in fullscreen)
2. Press the Windows button to minimize the app
3. Press the Monitorian system icon in the Windows taskbar (left click) and adjust brightness with your mouse scroll wheel only; (Monitorian system icon in the taskbar is configured by me to never minimized)
4. Jump right back into the previous app with Alt+Tab
5. Press the Windows button again to minimize the app and notice that Minitorian is still open

I usually perform these steps quickly, but the issue can be reproduced if you do it slow too. 
If I perform the same steps but adjust the brightness by clicking some point on the slider instead, Monitorian will disappear after adjusting my brightness and returning to the app, and this is my expected behavior for the app when I'm adjusting brightness using the scroll wheel.

**Comment by emoacht** [comment] 2023-07-12 16:18
Thanks for the report but I cannot reproduce.

> (Monitorian system icon in the taskbar is configured by me to never minimized)

What you actually do? What you mean by "never minimized"?

**Comment by realoctavian** [comment] 2023-07-12 19:04
This is how my setup looks.

https://imgur.com/a/34YICQH

Also, not sure if this is relevant, but I have a laptop and a monitor that I use with it. The monitor is configured to be the main display in Windows display settings. Everything that I described happens on the main (external) display.

**Comment by realoctavian** [comment] 2023-07-12 19:19
Sorry to double post but here's a video showcasing the issue: https://imgur.com/a/7VeZxAo

**Comment by emoacht** [comment] 2023-07-13 08:29
So you mean that you set this app's icon to always appear in in the taskbar by "never minimized".
It is unlikely that whether the monitor is main display or not or whether it is external or internal does matter.
Anyways, I cannot deny that such full-screen app could screw the focus management of this app but I cannot reproduce it.

**Comment by emoacht** [comment] 2023-07-16 23:40
It may be fixed by 7437131d0c10416ec8a8fbeaf5e28aa7576dedd0

**Closed** 2023-07-18 17:42 UTC

**Comment by realoctavian** [comment] 2023-07-19 10:58
I can confirm the issue has been fixed. Thank you very much!
