### ISSUE TITLE
Automatic screen rotation feature

### ISSUE THREAD

**Issue by ireun** [emoacht/Monitorian#57] opened 2019-10-31 09:27 UTC
Hello! 

I would like to suggest a neat little feature. Some monitors are equipped with accelerometer, thus, can detect screen orientation. One of the examples is HP z24n g2 that I own. This is handled by proprietary software installed on your PC. I'm not really willing to install a large HP monitor management software just to have this feature.

Since Monitorian already uses VCP commands to get and change brightness, it would be probably pretty easy to get the screen orientation. The VCP code for that is `0xAA`:
![image](https://user-images.githubusercontent.com/695818/67934776-d1004e80-fbc8-11e9-958b-ff792d55cfff.png)

The only problem with this, is that the app would need to periodically ( and frequently ) check to see if this value has changed. Which would eat up some resources. 

Tell me what You think!

**Comment by ireun** [comment] 2019-11-01 09:19
I made a small code snippet, that should do the trick. I know nothing of C# so it's in C++. https://gist.github.com/ireun/fc24cb66ec7b06a0be6f0fb50ce1a84f

**Comment by emoacht** [comment] 2019-11-04 07:03
Thank you for your suggestion and code.
The problem is how to catch the orientation change event. The polling as you suggested would not be a choice.
Although [DisplayInformation.OrientationChanged](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.orientationchanged) Event seems to be useful, it is only for UWP app. Then I have no idea right now.

**Comment by emoacht** [comment] 2019-11-04 22:08
I tried to check screen orientations by following code:
https://gist.github.com/emoacht/19ead120f96c104c793820998f39ecca
I found that my monitors do not return correct physical orientations (always angle 0). This approach seems no to be promising.

**Comment by ireun** [comment] 2019-11-04 22:15
I will test this approach this week, i'm sure my monitor outputs correct value.

**Comment by ireun** [comment] 2019-11-05 11:04
I used my code, it worked! As I said, your screen need accelerometer built in to support this feature, maybe yours just doesn't? 

https://streamable.com/20q84

**Comment by emoacht** [comment] 2019-11-05 23:29
I have no doubt about your code.
The point is that monitors which have built-in accelerometers are not so common.

**Comment by emoacht** [comment] 2019-12-03 04:33
I close this issue until any good technique found to capture the change of monitors rotation.

**Closed by emoacht** 2019-12-03 04:33 UTC
