### ISSUE TITLE
Adjust bar disappeared after switch between monitors

### ISSUE THREAD

**Issue by jwguo321** [emoacht/Monitorian#231] opened 2021-09-23 15:38 UTC
Hello,

my laptop is connected to the monitor via HDMI, the software works well when I used the laptop internal monitor, but after I switch the display mode to external monitor only, the adjust bar just disappeared and only monitor name was shown. To restore it, I need to restart the software,  Is it a bug?
![image](https://user-images.githubusercontent.com/49670668/134538737-4621efa4-5431-422c-8cf5-cc7edac5d734.png)

**Comment by jwguo321** [comment] 2021-09-23 15:40
> Hello,
> 
> my laptop is connected to the monitor via HDMI, the software works well when I used the laptop internal monitor, but after I switch the display mode to external monitor only, the adjust bar just disappeared and only monitor name was shown. To restore it, I need to restart the software, Is it a bug?
> ![image](https://user-images.githubusercontent.com/49670668/134538737-4621efa4-5431-422c-8cf5-cc7edac5d734.png)

After the app restarted：
![image](https://user-images.githubusercontent.com/49670668/134539161-964bd566-8c88-403e-9e70-410a9a066564.png)

**Comment by emoacht** [comment] 2021-09-23 21:51
Thanks for the report.
It might be something to do with the detection of monitors. Your external monitor might stop responding to this app when you changed the settings.
Could you post operation.log before and after this issues happened?

**Comment by jwguo321** [comment] 2021-09-24 02:00
> Thanks for the report.
> It might be something to do with the detection of monitors. Your external monitor might stop responding to this app when you changed the settings.
> Could you post operation.log before and after this issues happened?

Before(use internal monitor only):
[Date: 2021/9/24 9:57:17 Ver: 3.5.1.0]
Enabled

After(switch to external monitor only):
[Date: 2021/9/24 9:57:17 Ver: 3.5.1.0]
Enabled

[Date: 2021/9/24 9:59:02 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 9:59:02 Ver: 3.5.1.0]
ScanAsync [2021/9/24 9:59:02]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": Empty,
      "IsReachable": false,
      "IsBrightnessSupported": false,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": Empty,
        "IsReachable": false,
        "IsBrightnessSupported": false,
        "IsContrastSupported": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": false,
      "IsConfirmed": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 9:59:06 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 9:59:11 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 9:59:11 Ver: 3.5.1.0]
ScanAsync [2021/9/24 9:59:06]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

After restart the application:
[Date: 2021/9/24 10:00:00 Ver: 3.5.1.0]
Initiated

[Date: 2021/9/24 10:00:10 Ver: 3.5.1.0]
ScanAsync [2021/9/24 10:00:01]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

**Comment by emoacht** [comment] 2021-09-24 02:29
Thanks for the log.
I could make a hypothesis based on the state of __after (switch to external monitor only)__ but the state of __before (use internal monitor only)__ is almost empty. There may be a transition from before and after. Could you repost the log which includes the whole process from before to after?

**Comment by jwguo321** [comment] 2021-09-24 03:28
> Thanks for the log.
> I could make a hypothesis based on the state of **after (switch to external monitor only)** but the state of **before (use internal monitor only)** is almost empty. There may be a transition from before and after. Could you repost the log which includes the whole process from before to after?

Hello, 
I record the whole process again, and here is the log, hope this would help you, thanks. The scenario is I woke up the laptop while connecting to a external monitor(it works well because last time I lauched the app when the laptop was displayed on external monitor only), and then change the display mode to internal monitor(works well), and then change the display mode to external monitor(adjust bar disappeared again).
[Date: 2021/9/24 10:30:22 Ver: 3.5.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionLock 0)

[Date: 2021/9/24 10:30:22 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Suspend 0)
[Date: 2021/9/24 11:18:40 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 0)

[Date: 2021/9/24 11:18:45 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 1)

[Date: 2021/9/24 11:18:47 Ver: 3.5.1.0]
OnMonitorAccessFailed
Status: DdcFailed
Message: High level, Code: -1071241847, Message: An operation failed because a DDC/CI message had an invalid value in its command field.


[Date: 2021/9/24 11:18:48 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:18:45]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": Empty,
      "IsReachable": false,
      "IsBrightnessSupported": false,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 4,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:18:48 Ver: 3.5.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 0)

[Date: 2021/9/24 11:18:50 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 2)

[Date: 2021/9/24 11:18:53 Ver: 3.5.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 1)

[Date: 2021/9/24 11:18:58 Ver: 3.5.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 2)

[Date: 2021/9/24 11:18:59 Ver: 3.5.1.0]
OnMonitorAccessFailed
Status: DdcFailed
Message: High level, Code: -1071241847, Message: An operation failed because a DDC/CI message had an invalid value in its command field.


[Date: 2021/9/24 11:18:59 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:18:50]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:19:00 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 3)

[Date: 2021/9/24 11:19:09 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:19:00]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:19:10 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 4)

[Date: 2021/9/24 11:19:19 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:19:10]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:19:40 Ver: 3.5.1.0]
OnMonitorsChangeInferred (PowerWatcher Resume 5)

[Date: 2021/9/24 11:19:49 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:19:40]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,3840,2160,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,3840,2160,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:21:00 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 11:21:00 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:21:00]
{
  "Items": [
    {
      "Type": "WmiMonitorItem",
      "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
      "Description": "Generic PnP Monitor (Internal)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,2560,1600,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "WmiMonitorItem",
        "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
        "Description": "Generic PnP Monitor (Internal)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,2560,1600,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": false,
        "Brightness": 89,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "Generic PnP Monitor (Internal)",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:21:04 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 11:21:04 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:21:04]
{
  "Items": [
    {
      "Type": "WmiMonitorItem",
      "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
      "Description": "Generic PnP Monitor (Internal)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,2560,1600,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "WmiMonitorItem",
        "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
        "Description": "Generic PnP Monitor (Internal)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,2560,1600,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": false,
        "Brightness": 89,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "Generic PnP Monitor (Internal)",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:21:09 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 11:21:09 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:21:09]
{
  "Items": [
    {
      "Type": "WmiMonitorItem",
      "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
      "Description": "Generic PnP Monitor (Internal)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,2560,1600,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "WmiMonitorItem",
        "DeviceInstanceId": "DISPLAY\CSO1606\5&1c96aac0&2&UID4357",
        "Description": "Generic PnP Monitor (Internal)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,2560,1600,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": false,
        "Brightness": 89,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "Generic PnP Monitor (Internal)",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:21:52 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 11:21:53 Ver: 3.5.1.0]
ScanAsync [2021/9/24 11:21:52]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
      "Description": "LG ULTRAFINE",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": Empty,
      "IsReachable": false,
      "IsBrightnessSupported": false,
      "IsContrastSupported": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\GSM5BC1\5&1c96aac0&2&UID4356",
        "Description": "LG ULTRAFINE",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": Empty,
        "IsReachable": false,
        "IsBrightnessSupported": false,
        "IsContrastSupported": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "LG ULTRAFINE",
      "IsUnison": false,
      "IsControllable": false,
      "IsConfirmed": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 2021/9/24 11:21:56 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 2021/9/24 11:22:01 Ver: 3.5.1.0]
OnMonitorsChangeInferred (DisplayWatcher)

**Comment by emoacht** [comment] 2021-09-24 04:09
Thanks for the log again.
So the external monitor has been lost during the transition and then came back.
I think this is an issue of timing to notify the change of "IsControllable" property.

**Comment by emoacht** [comment] 2021-09-24 04:19
Could you try the attached version?
[MonitorianInstaller352.zip](https://github.com/emoacht/Monitorian/files/7222433/MonitorianInstaller352.zip)

**Comment by jwguo321** [comment] 2021-09-24 04:45
!> Could you try the attached version?
> [MonitorianInstaller352.zip](https://github.com/emoacht/Monitorian/files/7222433/MonitorianInstaller352.zip)

Hello, 
I've tried the attached version, and it works fine now. Thank you very much!

**Comment by emoacht** [comment] 2021-09-24 04:50
Thanks for the confirmation.
So the issue is identified. Please note I will delete the attached file shortly.

**Comment by jwguo321** [comment] 2021-09-24 04:53
> Thanks for the confirmation.
> So the issue is identified. Please note I will delete the attached file shortly.

OK, by the way, will this problem be resolved in your next release?

**Comment by emoacht** [comment] 2021-09-24 07:18
Yes, it will come soon.
I have to write a long explanation on how it happens.

**Comment by emoacht** [comment] 2021-09-30 00:04
Released as Ver 3.6

**Closed by emoacht** 2021-09-30 00:04 UTC
