### ISSUE TITLE
Monitorian stops recognizing compatibility

### ISSUE THREAD

**Issue by jim829** [emoacht/Monitorian#125] opened 2021-01-22 16:35 UTC
Version 2.10.1.0
Windows 10 Pro 20H2
Nvidia 1070
Monitors: MSI MAG274

Version 2.10.1.0
Windows 10 Home 20H2
Nvidia 1060
Monitors: Pixio 325c

This happened on two PCs with two different monitors. On first install it recognized they were controllable but eventually within a day it stopped working. I also had a Samsung 27" monitor that was a few years old and Monitorian worked well with it for a couple years. The MAG274 brightness could be controlled easily enough when I boot into Linux and use DDCtools to control with a hotkey and as said, Monitorian did work with it for about a day. The brightness control worked fine, but soon quit recognizing it was controllable.

Edit: Changed version

**Comment by emoacht** [comment] 2021-01-22 22:22
Thank you for the report.
Could you clarify what you mean by "stopped working"?
It is possible that this app fails to access the monitor consecutively and determines it as not controllable.
Could you provide Probe.log as well as Operations.log when starts this app and when the issue happens.
It will be the starting point to dig into the issue. I am a little bit tired of people who make claims but provide no meaning information.

**Comment by jim829** [comment] 2021-01-23 01:39
By stopped working I mean I get "Monitor is not controllable" and "DDC/CI is not supported or enabled". I can't reproduce it now but if you keep this issue open for a few more days I can investigate and try with different drivers and configurations.  Nvidia driver is 461.09 on both PCs which I've learned can be relevant as on Linux, Nvidia drivers may have I2C communication failures on some cards so you have to do [this workaround](https://www.ddcutil.com/nvidia/). Here's [probe.log](https://pastebin.com/raw/W6qgQaqu) for the current monitor.

**Comment by emoacht** [comment] 2021-01-23 04:41
Thank you for the log and explanation.
If it is caused by the driver, there would be little which can be done at the application level.

**Comment by jim829** [comment] 2021-01-23 20:41
No luck after changing driver version. I tried another open source app on the Windows store that adjusts external monitor brightness using DDC protocol yesterday and at first it didn't work. I uninstalled and today installed again and it works on current and other said monitor. I'd love for your app to work with them though because an 80MB app to adjust monitor brightness, something your app can do in 500KB, is bloat personified.

**Comment by emoacht** [comment] 2021-01-23 22:46
I see. Then could you upload probe.log and operation.log when the issue happens?

**Comment by jim829** [comment] 2021-01-23 23:25
Sure will. By issue, I guess you mean when it doesn't work but if I could reproduce and provide logs when it's working I would if it happens. [Operation.log](https://pastebin.com/raw/yPTxp8hC) and [probe.log](https://pastebin.com/raw/xqMJ9NYQ). I've tried turning freesync off/on and made sure dynamic brightness is off or any other potentially interfering settings. I also tried another DDC program and it works to control brightness with this monitor.

**Comment by emoacht** [comment] 2021-01-24 00:16
Thanks you for the logs.
Apparently DDC/CI has turned to be unusable.
I don't know how other apps work but you can try to change the configuration of the methods to access a monitor: [MonitorConfiguration.GetBrightness](https://github.com/emoacht/Monitorian/blob/83ef59d26b19293e8eac133651f02ed989ef6f54/Source/Monitorian.Core/Models/Monitor/MonitorConfiguration.cs#L364) and [MonitorConfiguration.SetBrightness](https://github.com/emoacht/Monitorian/blob/83ef59d26b19293e8eac133651f02ed989ef6f54/Source/Monitorian.Core/Models/Monitor/MonitorConfiguration.cs#L417).

**Comment by jim829** [comment] 2021-01-24 08:46
Yeah, I could if I was a competent programmer but my experience with C was very short and in a galaxy long ago and far away. Nirsoft's controlmymonitor is what I'm currently using with a custom hotkey script, it works well and very small fingerprint, but it's closed source. I'd rather use something open source like yours if I could.

**Comment by emoacht** [comment] 2021-01-27 07:53
For information for interested people, I think that most apps use the same Win32 APIs internally to access external monitors and if an app succeeds but another fails, it would be caused by the difference on the way to call those APIs. Naturally, it would be possible to find better way to call those API by changing the parameters.

I close this issue but if new information is found, feel free to post it here.

**Closed by emoacht** 2021-01-27 07:53 UTC
