### ISSUE TITLE
All monitors show up as "Generic PnP Monitor"

### ISSUE THREAD

**Issue by Raytar** [emoacht/Monitorian#8] opened 2018-08-16 18:04 UTC
Hi,
All my monitors are showing up as "Generic PnP Monitor", which makes it difficult to tell them apart.
This is what it looks like: 
![image](https://user-images.githubusercontent.com/10762082/44224686-79c0ba80-a18b-11e8-83a1-50f9d4eacf67.png)

I can think of a few ways to improve this:

1. Show the display number next to the description.
2. Show whether the display is "primary" or "secondary".
3. There's a new [API available](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.displaymonitor) in Windows 10 version 1803 that promises to "get a friendly name for the device suitable for display to a user." I have experimented with integrating this API, and the result looks like this: 
![image](https://user-images.githubusercontent.com/10762082/44224889-31ee6300-a18c-11e8-8eeb-4d635f5a54c0.png)
([Here is the commit](https://github.com/Raytar/Monitorian/commit/bed6d818fc63fd90b2806ec758f4bdb0771a1b0c))
Obviously, this breaks compatibility with older Windows versions, and I don't know how to work around that, as I'm new to .NET and UWP programming. Maybe use it only on the Microsoft Store version?

Thank you for making this tool, it works great!

Regards,
John

**Comment by emoacht** [comment] 2018-08-16 23:01
Hi John,
Thanks for your information and suggestion.
To call this new UWP API while retaining the compatibility with older OSes, we need to make that part separate library like StartupBridge in this solution.
Before that, I would like to make sure how your monitors are seen from other APIs. Could you get a log file as described in "Development" section in readme and upload it? 
emoacht

**Comment by Raytar** [comment] 2018-08-17 07:47
Here are the contents of the log file:
```
[Date: 17 Aug 2018 09:44:55]
{
  "Device Context - DeviceItems": [
    {
      "DeviceInstanceId": "DISPLAY\\BNQ78D6\\5&26238897&0&UID4353",
      "Description": "Generic PnP Monitor",
      "DisplayIndex": 1,
      "MonitorIndex": 0
    },
    {
      "DeviceInstanceId": "DISPLAY\\BNQ7842\\5&26238897&0&UID4352",
      "Description": "Generic PnP Monitor",
      "DisplayIndex": 2,
      "MonitorIndex": 0
    }
  ],
  "Monitor Configuration - PhysicalItems": [
    {
      "Key": {
        "DisplayIndex": 1
      },
      "Value": [
        {
          "Description": "Generic PnP Monitor",
          "IsBrightnessSupported": true,
          "IsLowLevel": false,
          "MonitorIndex": 0
        }
      ]
    },
    {
      "Key": {
        "DisplayIndex": 2
      },
      "Value": [
        {
          "Description": "Generic PnP Monitor",
          "IsBrightnessSupported": true,
          "IsLowLevel": true,
          "MonitorIndex": 0
        }
      ]
    }
  ],
  "Device Installation - InstalledItems": [
    {
      "DeviceInstanceId": "DISPLAY\\BNQ7842\\5&26238897&0&UID4352",
      "Description": "Generic PnP Monitor",
      "IsRemovable": true
    },
    {
      "DeviceInstanceId": "DISPLAY\\BNQ78D6\\5&26238897&0&UID4353",
      "Description": "Generic PnP Monitor",
      "IsRemovable": true
    }
  ],
  "MSMonitorClass - DesktopItems": [ ]
}
```

**Comment by emoacht** [comment] 2018-08-18 23:59
Thanks, John.
Okay, I understand the situation.
I added a separate project to use Windows.Devices.Display.DisplayMonitor functions and improved the operation. It will use DisplayName value if descriptions from older API are "Generic PnP Monitor" and DisplayName value is not empty because I found the value may be empty in case of internal monitors.
Check the following commits in develop branch:
https://github.com/emoacht/Monitorian/commit/4db08ee345ea7db08042587e44432a2aebeacb46
https://github.com/emoacht/Monitorian/commit/8906b1d6dfbcd170822b0636c450aad192300ba7

**Comment by Raytar** [comment] 2018-08-19 15:03
Thank you! I will try this when I have time!

**Comment by Raytar** [comment] 2018-08-20 10:47
I have tested it on 3 machines (all running Windows 10 version 1803) and it works great with the exception being the built-in monitor on my laptop (thinkpad x240) which still shows up as "Generic PnP Monitor". External monitors connected to the laptop did get the correct names, though. FYI, windows display settings doesn't show any name for the built-in monitor either, so I guess it doesn't have a name.

**Comment by emoacht** [comment] 2018-08-20 13:06
Thanks for your confirmation.
As for the case of ThinkPad X240, if its internal monitor does not have its own name, it is also the case for my ThinkPad X230, it is exactly expected behavior.
I will close this issue by another commit.

**Closed** 2018-08-21 19:26 UTC
Labels: enhancement
