### ISSUE TITLE
"This monitor is not controllable" randomly after hibernation

### ISSUE THREAD

**Issue by Intenditore** [emoacht/Monitorian#50] opened 2019-08-27 10:00 UTC
I'm freaking tired of this(

![2019-08-27_12-22-28](https://user-images.githubusercontent.com/20087729/63761902-8f061400-c8ca-11e9-83ec-b31fc42b3587.png)

**Comment by Romanelo** [comment] 2019-09-01 12:41
![Аннотация 2019-09-01 153854](https://user-images.githubusercontent.com/15716960/64076521-a714d380-ccce-11e9-8f9b-9108f8bbbf27.png)
also on my monitor or something!, DDC/CI enabled

**Comment by Romanelo** [comment] 2019-09-01 12:46
after the closure of the despetcher task
![Аннотация 2019-08-31 165022](https://user-images.githubusercontent.com/15716960/64076612-ad577f80-cccf-11e9-850f-c220e5b68d2b.png)

**Comment by Intenditore** [comment] 2019-09-01 12:47
I have to perform the same thing, only restarting the program helps

**Comment by emoacht** [comment] 2019-09-03 11:39
Hi,
In general, it happens immediately after the resume from suspend or hibernation because the system is not yet ready to work with monitors when this app scans them. The resume event will trigger this app to rescan the connected monitors several times in the period of around 2 minutes. During such period, the system is expected to be ready so that this app can work again.
It seems that something went wrong in this process. To figure out the issue, could you perform the probe function as explained in readme in several times after the resume?

**Comment by Intenditore** [comment] 2019-09-04 20:44
I did it. One is when the bug appears, another after restarting app
[probe_disabled.log](https://github.com/emoacht/Monitorian/files/3576413/probe_disabled.log)
[probe_enabled.log](https://github.com/emoacht/Monitorian/files/3576414/probe_enabled.log)

**Comment by emoacht** [comment] 2019-09-15 13:04
@Intenditore Thanks for the logs.
However, unfortunately, the log does not capture the situation when the monitor in question returns an erroneous response so as to cause this issue. Ideally, to make sure when exactly happens, the responses during the multiple timing after the resume are necessary. It means immediately after the resume, 5 seconds, 10 seconds, 20 seconds, 40 seconds, 80 seconds and 160 seconds after the resume.
Its not a simple bug but finding the way to handle the erroneous response from some monitors as gracefully as possible.

**Comment by emoacht** [comment] 2019-10-13 13:48
Modified by 91d1563f5d19d0fd66119c900ccd9b3cec99887b
It changes the condition to determine the controllable state of a monitor.

**Comment by Intenditore** [comment] 2019-11-10 15:33
> 
> 
> Modified by [91d1563](https://github.com/emoacht/Monitorian/commit/91d1563f5d19d0fd66119c900ccd9b3cec99887b)
> It changes the condition to determine the controllable state of a monitor.

Sorry, but it's not really working. I get the message (glowing red now :D) much more frequently and does not go away for a long time forcing me to restart the app. Here's the log collected when this message appears.
[probe.log](https://github.com/emoacht/Monitorian/files/3828630/probe.log)

**Comment by emoacht** [comment] 2019-11-15 04:28
Thank you for the report.
I found that in some cases, a rush of messages interrupts the sequence of re-scanning monitors and it may cause an accumulation of failure counts almost instantly. To solve this issue, I reconfigured the scan timings in 4ea9edf1d7e2addfa09f57f752fc35fd26f7e3b7 and set interval for scan in 794549de4263227c96f7da173524eed746bd76b4.

**Comment by Intenditore** [comment] 2019-11-17 12:18
Weird, I updated to 2.1.0, but the problem persists

**Comment by emoacht** [comment] 2019-11-17 19:01
It is implemented in Ver 2.2.0. Try its [pre-release](https://github.com/emoacht/Monitorian/releases/download/2.2.0-Executables/Monitorian220.zip).

**Comment by Intenditore** [comment] 2019-12-12 22:41
Dear @emoacht, you will laugh, but... It happened again! 
[probe.log](https://github.com/emoacht/Monitorian/files/3958097/probe.log)

**Comment by emoacht** [comment] 2019-12-13 14:02
Thank you for reporting again.
For the moment, try Ver 2.3.0 and see if there would be any difference.

**Comment by emoacht** [comment] 2019-12-30 17:15
If this issue happens again, try Ver 2.4.0 with making operation log as described in readme. The operation log would provide much better information to track what really happens.

**Comment by chivoyage** [comment] 2020-03-10 21:54
This happens to me all the time on 2.4.0 after waking up from sleep. Only restarting helps. In the last version, even restarting didn't help at time but in 2.4.0, restarting helps each time. But still, seeing this bug all the time makes it annoying.

**Comment by emoacht** [comment] 2020-03-11 22:40
I see.
Make and save operation.log as described in readme and post it with the time when the issue happened.

**Comment by chivoyage** [comment] 2020-03-15 09:28
[operation.log](https://github.com/emoacht/Monitorian/files/4333970/operation.log)
Happens right after a PC resume from sleep. But it's been fixing itself if given a bit of time. 
![Screenshot (38)](https://user-images.githubusercontent.com/30416710/76698853-b4604100-66a7-11ea-9a9c-2a0100bad544.png)

**Comment by emoacht** [comment] 2020-03-16 12:21
@chivoyage Thanks for the log.
It tells that:
15/03/2020 10:23:51 - OS resumed.
15/03/2020 10:23:52 - The first scan after resume found that the monitor is unreachable. It means that OS did not return expected response to API calls. It is quite common immediately after resume.
15/03/2020 10:23:58 - The second scan after resume found the monitor returned to normal.
So you had only 6 seconds window. You are very good at taking the screenshot!

Well, there is nothing surprising. The monitor returned to normal state within very short period. It is completely expected behavior.

**Comment by chivoyage** [comment] 2020-03-16 14:00
In this case, it returned quickly but sometimes, I click the tray icon like 25 times for 1-2 minutes and it's the same message. I'll post a video and log soon.



________________________________

**Comment by chivoyage** [comment] 2020-03-16 21:32
Here's a video - https://youtu.be/cwGmIeVX2ec (Wait for HD to process)
This log is the one I produced at the end in the video.
[operation.log](https://github.com/emoacht/Monitorian/files/4340474/operation.log)

Thanks,
Chi

**Comment by chivoyage** [comment] 2020-04-30 22:06
Had a few more instances where even restarting the app multiple times didn't help but then I realised that restarting the graphics drivers helps. (ctrl+shift+win+b) I'm using Nvidia.

**Comment by emoacht** [comment] 2020-07-29 05:51
I close this issue because it seems to related to #75

**Closed by emoacht** 2020-07-29 05:51 UTC
