### ISSUE TITLE
Exception at start

### ISSUE THREAD

**Issue by shmykelsa** [emoacht/Monitorian#22] opened 2018-11-13 21:57 UTC
[exception.log](https://github.com/emoacht/Monitorian/files/2578307/exception.log)

**Comment by emoacht** [comment] 2018-11-14 18:33
Hi shemyklsa,
Thank you for reporting.
Although it is not clear from the log where the cause is, I guess it lies not inside the app but outside of the app. Does your system fulfill the requirements?

**Comment by emoacht** [comment] 2018-11-23 21:01
Without further information, I will close this issue shortly.

**Closed** 2018-11-25 12:56 UTC
