### ISSUE TITLE
High CPU usage on re-orienting displays

### ISSUE THREAD

**Issue by jacksongoode** [emoacht/Monitorian#275] opened 2022-01-02 20:53 UTC
For whatever reason, when changing the orientation/extension of displays (perhaps on new displays being connected as well?) the CPU will spike under the process Runtime Broker a child of which is Monitorian. It's enough to lag the mouse and spike the fans on my laptop.

**Comment by emoacht** [comment] 2022-01-03 00:37
When display settings is changed, this app will rescan monitors. It is normal.
If it cause substantial lag, post [operation.log](https://github.com/emoacht/Monitorian#operations) which includes the time when the setting changed.
BTW, what do you mean by "extension of displays"?

**Comment by jacksongoode** [comment] 2022-01-03 04:17
[operation.log](https://github.com/emoacht/Monitorian/files/7800421/operation.log)
Here's the log. I just meant that the lag was caused not only by connecting or disconnecting displays but also by arranging displays (duplicating/extending, etc.)

**Comment by emoacht** [comment] 2022-01-03 04:49
Thanks for the log.
It looks quite normal.

> I just meant that the lag was caused not only by connecting or disconnecting displays but also by arranging displays (duplicating/extending, etc.)

Yes, "arranging displays (duplicating/extending, etc.)" is a kind of change of display settings and so it will triger rescan. It is normal behavior.

**Comment by jacksongoode** [comment] 2022-01-03 18:35
That's really surprising that querying the displays and DDC info has such a high cost. I use a similar application in Linux and there's next to no utilization. Might it be some cause for investigation?

**Comment by emoacht** [comment] 2022-01-03 23:18
Are you sure that CPU usage spike is caused by this app?
It happens when this app starts?

**Comment by emoacht** [comment] 2022-01-07 03:16
I have a good reason to doubt that the spike in question is caused by this app. When I manually triggered [rescan](https://github.com/emoacht/Monitorian#rescan) on Surface Pro 8, I only noticed a moderate rise of CPU usage around less than 10%. Of course it depends on each system though.
If no further information, I will close this issue.

**Comment by jacksongoode** [comment] 2022-01-07 03:17
Is there a way I could record process utilization for a log for you?

**Comment by emoacht** [comment] 2022-01-07 03:40
I am not an expert on this. But you can check CPU usage for each process by resource monitor.

**Closed** 2022-01-18 15:24 UTC

**Comment by jacksongoode** [comment] 2022-01-25 16:28
Just to follow up with this, I've been studying the CPU use and your correct that on start or on monitor rescan it reaches only 20% but there are stutters that affect the mouse happen consistently every 1/4s for about 5 seconds. I can tell this by dragging the cursor across the screen and watching the timing of the stutters.

**Comment by piotrp** [comment] 2024-01-30 19:39
@emoacht also stutters on my system: around 5-10 seconds, on each refresh, so each time my computer comes out of sleep.

Tests i performed:
1. Only laptop screen, no external monitors - works fine
2. Laptop screen (doesn't matter whether it's active, i.e. lid open, or disabled, i.e. lid closed) + two external monitors connected via USB-C with MST (Dell U2422HE + U2422H or U2722DE + U2722D) - stutter
3. Laptop screen (doesn't matter whether it's active, i.e. lid open, or disabled, i.e. lid closed) + single external monitor connected via USB-C (Dell U2422HE) - stutter, but I'd say half as strong

[probe.log](https://github.com/emoacht/Monitorian/files/14103166/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/14103167/operation.log)

After initial stutter everything works fine - brightness changes are smooth.

CPU doesn't go above a few percent, looks more like something locking up my system. Maybe some system call is expensive/broken. I have a Lenovo laptop (P1 Gen 5 with RTX 3070 Ti).

I tried Twinkle Tray and it behaved the same.

**Comment by piotrp** [comment] 2024-01-30 21:02
If I'm reading this ETW trace correctly then the culprit is somewhere in nVidia's driver:
![obraz](https://github.com/emoacht/Monitorian/assets/1409807/2ebbeeb5-b801-421e-a652-f43f5f753cda)
(almost all the time of `GetCapabilitiesStringLength` is attributed to functions in nvlddmkm.sys).

So it looks like a driver or driver+monitor compatibility issue.
